### PR TITLE
F/validate cmd concat

### PR DESCRIPTION
**Pull request by faxm0dem**
This has been running on our production environment for a while now.
Leaving this here as a reminder, you can merge this as soon as you believe it's fortunate to abandon support of puppet < 3.5

### CODE REVIEW

**Comment by ihrwein** [comment]
I checked and the 3.5 release is a year old now. If I upgrade the Travis CI check to use puppet 3.5 and above, would you rebase your PR?

**Comment by faxm0dem** [comment]
sure thing!

**Comment by faxm0dem** [comment]
any news? Are you still waiting for something?

**Comment by ihrwein** [comment]
Sorry for the lack of communication, I forget about this.

**Pull request merged**
